[package]
name = "double_array_trie"
version = "0.1.0"
authors = ["Yuichiro Sawai <sawai.yuichiro.sn0@is.naist.jp>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
failure = "0.1"
flate2 = "1.0"

[dev-dependencies]
rand = "0.5"
tempfile = "3"